# Generated by Django 5.2.4 on 2025-08-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit_date',
            field=models.DateField(blank=True, default=None, help_text='Date of the last visit to the hospital', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', help_text="Patient's current status", max_length=10),
        ),
    ]
