# Generated by Django 5.2.4 on 2025-08-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_last_visit_date_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the last visit or any additional notes', null=True),
        ),
    ]
