# Generated by Django 5.2.4 on 2025-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='pending', help_text="Patient's current status", max_length=100),
        ),
    ]
