# Generated by Django 5.2.4 on 2025-08-20 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the last visit or any additional note', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('PENDING', 'Pending')], default='PENDING', help_text="Patient's current status", max_length=100),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital_patient_id'], name='patient_pat_hospita_1aa4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name'], name='patient_pat_first_n_b4754d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name'], name='patient_pat_last_na_f630ca_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='patient_pat_phone_n_8511f4_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='patient_pat_email_ac4080_idx'),
        ),
    ]
