# Generated by Django 5.2.4 on 2025-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='SCHEDULED', max_length=100),
        ),
    ]
